package ast

type Visitor interface {
	Visit(files []File) (any, error)
	VisitExpr(Expr) (any, error)
	VisitAtomExpr(*AtomExpr) (any, error)
	VisitUnaryExpr(*UnaryExpr) (any, error)
	VisitBinaryExpr(*BinaryExpr) (any, error)
	VisitFunctionCallExpr(*FunctionCallExpr) (any, error)
	VisitStmt(Stmt) (any, error)
	VisitExprStmt(*ExprStmt) (any, error)
	VisitPrintStmt(*PrintStmt) (any, error)
	VisitStructDefStmt(*StructDefStmt) (any, error)
	VisitReturnStmt(*ReturnStmt) (any, error)
	VisitFuncDefStmt(*FuncDefStmt) (any, error)
	VisitVarDefStmt(*VarDefStmt) (any, error)
	VisitModuleDefStmt(*ModuleDefStmt) (any, error)
	VisitType(Type) (any, error)
	VisitNamedT(*NamedT) (any, error)
	VisitIntT(*IntT) (any, error)
	VisitFloatT(*FloatT) (any, error)
	VisitStringT(*StringT) (any, error)
	VisitFunctionT(*FunctionT) (any, error)
	VisitStructT(*StructT) (any, error)
}
